package org.bukkit;

public enum Material {
    AIR,
    STONE,
    GRANITE,
    POLISHED_GRANITE, 
    DIORITE,
    POLISHED_DIORITE,
    ANDESITE,
    POLISHED_ANDESITE,
    
    DEEPSLATE,
    COBBLED_DEEPSLATE,
    POLISHED_DEEPSLATE,
    CALCITE,
    TUFF,
    DRIPSTONE_BLOCK,
    
    GRASS_BLOCK,
    DIRT,
    COARSE_DIRT,
    
    PODZOL,
    ROOTED_DIRT,
    MUD,
    CRIMSON_NYLIUM,
    WARPED_NYLIUM,
    COBBLESTONE,
    OAK_PLANKS,
    SPRUCE_PLANKS,
    BIRCH_PLANKS,
    JUNGLE_PLANKS,
    ACACIA_PLANKS,
    CHERRY_PLANKS,
    DARK_OAK_PLANKS,
    MANGROVE_PLANKS,
    BAMBOO_PLANKS,
    CRIMSON_PLANKS,
    WARPED_PLANKS,
    BAMBOO_MOSAIC,
    
    OAK_SAPLING,
    
    SPRUCE_SAPLING,
    
    BIRCH_SAPLING,
    
    JUNGLE_SAPLING,
    
    ACACIA_SAPLING,
    
    CHERRY_SAPLING,
    
    DARK_OAK_SAPLING,
    
    MANGROVE_PROPAGULE,
    BEDROCK,
    SAND,
    
    SUSPICIOUS_SAND,
    
    SUSPICIOUS_GRAVEL,
    RED_SAND,
    GRAVEL,
    COAL_ORE,
    DEEPSLATE_COAL_ORE,
    IRON_ORE,
    DEEPSLATE_IRON_ORE,
    COPPER_ORE,
    DEEPSLATE_COPPER_ORE,
    GOLD_ORE,
    DEEPSLATE_GOLD_ORE,
    
    REDSTONE_ORE,
    
    DEEPSLATE_REDSTONE_ORE,
    EMERALD_ORE,
    DEEPSLATE_EMERALD_ORE,
    LAPIS_ORE,
    DEEPSLATE_LAPIS_ORE,
    DIAMOND_ORE,
    DEEPSLATE_DIAMOND_ORE,
    NETHER_GOLD_ORE,
    NETHER_QUARTZ_ORE,
    ANCIENT_DEBRIS,
    COAL_BLOCK,
    RAW_IRON_BLOCK,
    RAW_COPPER_BLOCK,
    RAW_GOLD_BLOCK,
    AMETHYST_BLOCK,
    BUDDING_AMETHYST,
    IRON_BLOCK,
    COPPER_BLOCK,
    GOLD_BLOCK,
    DIAMOND_BLOCK,
    NETHERITE_BLOCK,
    EXPOSED_COPPER,
    WEATHERED_COPPER,
    OXIDIZED_COPPER,
    CUT_COPPER,
    EXPOSED_CUT_COPPER,
    WEATHERED_CUT_COPPER,
    OXIDIZED_CUT_COPPER,
    
    CUT_COPPER_STAIRS,
    
    EXPOSED_CUT_COPPER_STAIRS,
    
    WEATHERED_CUT_COPPER_STAIRS,
    
    OXIDIZED_CUT_COPPER_STAIRS,
    
    CUT_COPPER_SLAB,
    
    EXPOSED_CUT_COPPER_SLAB,
    
    WEATHERED_CUT_COPPER_SLAB,
    
    OXIDIZED_CUT_COPPER_SLAB,
    WAXED_COPPER_BLOCK,
    WAXED_EXPOSED_COPPER,
    WAXED_WEATHERED_COPPER,
    WAXED_OXIDIZED_COPPER,
    WAXED_CUT_COPPER,
    WAXED_EXPOSED_CUT_COPPER,
    WAXED_WEATHERED_CUT_COPPER,
    WAXED_OXIDIZED_CUT_COPPER,
    
    WAXED_CUT_COPPER_STAIRS,
    
    WAXED_EXPOSED_CUT_COPPER_STAIRS,
    
    WAXED_WEATHERED_CUT_COPPER_STAIRS,
    
    WAXED_OXIDIZED_CUT_COPPER_STAIRS,
    
    WAXED_CUT_COPPER_SLAB,
    
    WAXED_EXPOSED_CUT_COPPER_SLAB,
    
    WAXED_WEATHERED_CUT_COPPER_SLAB,
    
    WAXED_OXIDIZED_CUT_COPPER_SLAB,
    
    OAK_LOG,
    
    SPRUCE_LOG,
    
    BIRCH_LOG,
    
    JUNGLE_LOG,
    
    ACACIA_LOG,
    
    CHERRY_LOG,
    
    DARK_OAK_LOG,
    
    MANGROVE_LOG,
    
    MANGROVE_ROOTS,
    
    MUDDY_MANGROVE_ROOTS,
    
    CRIMSON_STEM,
    
    WARPED_STEM,
    
    BAMBOO_BLOCK,
    
    STRIPPED_OAK_LOG,
    
    STRIPPED_SPRUCE_LOG,
    
    STRIPPED_BIRCH_LOG,
    
    STRIPPED_JUNGLE_LOG,
    
    STRIPPED_ACACIA_LOG,
    
    STRIPPED_CHERRY_LOG,
    
    STRIPPED_DARK_OAK_LOG,
    
    STRIPPED_MANGROVE_LOG,
    
    STRIPPED_CRIMSON_STEM,
    
    STRIPPED_WARPED_STEM,
    
    STRIPPED_OAK_WOOD,
    
    STRIPPED_SPRUCE_WOOD,
    
    STRIPPED_BIRCH_WOOD,
    
    STRIPPED_JUNGLE_WOOD,
    
    STRIPPED_ACACIA_WOOD,
    
    STRIPPED_CHERRY_WOOD,
    
    STRIPPED_DARK_OAK_WOOD,
    
    STRIPPED_MANGROVE_WOOD,
    
    STRIPPED_CRIMSON_HYPHAE,
    
    STRIPPED_WARPED_HYPHAE,
    
    STRIPPED_BAMBOO_BLOCK,
    
    OAK_WOOD,
    
    SPRUCE_WOOD,
    
    BIRCH_WOOD,
    
    JUNGLE_WOOD,
    
    ACACIA_WOOD,
    
    CHERRY_WOOD,
    
    DARK_OAK_WOOD,
    
    MANGROVE_WOOD,
    
    CRIMSON_HYPHAE,
    
    WARPED_HYPHAE,
    
    OAK_LEAVES,
    
    SPRUCE_LEAVES,
    
    BIRCH_LEAVES,
    
    JUNGLE_LEAVES,
    
    ACACIA_LEAVES,
    
    CHERRY_LEAVES,
    
    DARK_OAK_LEAVES,
    
    MANGROVE_LEAVES,
    
    AZALEA_LEAVES,
    
    FLOWERING_AZALEA_LEAVES,
    SPONGE,
    WET_SPONGE,
    GLASS,
    TINTED_GLASS,
    LAPIS_BLOCK,
    SANDSTONE,
    CHISELED_SANDSTONE,
    CUT_SANDSTONE,
    COBWEB,
    GRASS,
    FERN,
    AZALEA,
    FLOWERING_AZALEA,
    DEAD_BUSH,
    SEAGRASS,
    
    SEA_PICKLE,
    WHITE_WOOL,
    ORANGE_WOOL,
    MAGENTA_WOOL,
    LIGHT_BLUE_WOOL,
    YELLOW_WOOL,
    LIME_WOOL,
    PINK_WOOL,
    GRAY_WOOL,
    LIGHT_GRAY_WOOL,
    CYAN_WOOL,
    PURPLE_WOOL,
    BLUE_WOOL,
    BROWN_WOOL,
    GREEN_WOOL,
    RED_WOOL,
    BLACK_WOOL,
    DANDELION,
    POPPY,
    BLUE_ORCHID,
    ALLIUM,
    AZURE_BLUET,
    RED_TULIP,
    ORANGE_TULIP,
    WHITE_TULIP,
    PINK_TULIP,
    OXEYE_DAISY,
    CORNFLOWER,
    LILY_OF_THE_VALLEY,
    WITHER_ROSE,
    TORCHFLOWER,
    
    PITCHER_PLANT,
    SPORE_BLOSSOM,
    BROWN_MUSHROOM,
    RED_MUSHROOM,
    CRIMSON_FUNGUS,
    WARPED_FUNGUS,
    CRIMSON_ROOTS,
    WARPED_ROOTS,
    NETHER_SPROUTS,
    
    WEEPING_VINES,
    
    TWISTING_VINES,
    
    SUGAR_CANE,
    
    KELP,
    MOSS_CARPET,
    
    PINK_PETALS,
    MOSS_BLOCK,
    
    HANGING_ROOTS,
    
    BIG_DRIPLEAF,
    
    SMALL_DRIPLEAF,
    
    BAMBOO,
    
    OAK_SLAB,
    
    SPRUCE_SLAB,
    
    BIRCH_SLAB,
    
    JUNGLE_SLAB,
    
    ACACIA_SLAB,
    
    CHERRY_SLAB,
    
    DARK_OAK_SLAB,
    
    MANGROVE_SLAB,
    
    BAMBOO_SLAB,
    
    BAMBOO_MOSAIC_SLAB,
    
    CRIMSON_SLAB,
    
    WARPED_SLAB,
    
    STONE_SLAB,
    
    SMOOTH_STONE_SLAB,
    
    SANDSTONE_SLAB,
    
    CUT_SANDSTONE_SLAB,
    
    PETRIFIED_OAK_SLAB,
    
    COBBLESTONE_SLAB,
    
    BRICK_SLAB,
    
    STONE_BRICK_SLAB,
    
    MUD_BRICK_SLAB,
    
    NETHER_BRICK_SLAB,
    
    QUARTZ_SLAB,
    
    RED_SANDSTONE_SLAB,
    
    CUT_RED_SANDSTONE_SLAB,
    
    PURPUR_SLAB,
    
    PRISMARINE_SLAB,
    
    PRISMARINE_BRICK_SLAB,
    
    DARK_PRISMARINE_SLAB,
    SMOOTH_QUARTZ,
    SMOOTH_RED_SANDSTONE,
    SMOOTH_SANDSTONE,
    SMOOTH_STONE,
    BRICKS,
    BOOKSHELF,
    
    CHISELED_BOOKSHELF,
    
    DECORATED_POT,
    MOSSY_COBBLESTONE,
    OBSIDIAN,
    TORCH,
    
    END_ROD,
    
    CHORUS_PLANT,
    
    CHORUS_FLOWER,
    PURPUR_BLOCK,
    
    PURPUR_PILLAR,
    
    PURPUR_STAIRS,
    SPAWNER,
    
    CHEST,
    CRAFTING_TABLE,
    
    FARMLAND,
    
    FURNACE,
    
    LADDER,
    
    COBBLESTONE_STAIRS,
    
    SNOW,
    ICE,
    SNOW_BLOCK,
    
    CACTUS,
    CLAY,
    
    JUKEBOX,
    
    OAK_FENCE,
    
    SPRUCE_FENCE,
    
    BIRCH_FENCE,
    
    JUNGLE_FENCE,
    
    ACACIA_FENCE,
    
    CHERRY_FENCE,
    
    DARK_OAK_FENCE,
    
    MANGROVE_FENCE,
    
    BAMBOO_FENCE,
    
    CRIMSON_FENCE,
    
    WARPED_FENCE,
    PUMPKIN,
    
    CARVED_PUMPKIN,
    
    JACK_O_LANTERN,
    NETHERRACK,
    SOUL_SAND,
    SOUL_SOIL,
    
    BASALT,
    
    POLISHED_BASALT,
    SMOOTH_BASALT,
    SOUL_TORCH,
    GLOWSTONE,
    INFESTED_STONE,
    INFESTED_COBBLESTONE,
    INFESTED_STONE_BRICKS,
    INFESTED_MOSSY_STONE_BRICKS,
    INFESTED_CRACKED_STONE_BRICKS,
    INFESTED_CHISELED_STONE_BRICKS,
    
    INFESTED_DEEPSLATE,
    STONE_BRICKS,
    MOSSY_STONE_BRICKS,
    CRACKED_STONE_BRICKS,
    CHISELED_STONE_BRICKS,
    PACKED_MUD,
    MUD_BRICKS,
    DEEPSLATE_BRICKS,
    CRACKED_DEEPSLATE_BRICKS,
    DEEPSLATE_TILES,
    CRACKED_DEEPSLATE_TILES,
    CHISELED_DEEPSLATE,
    REINFORCED_DEEPSLATE,
    
    BROWN_MUSHROOM_BLOCK,
    
    RED_MUSHROOM_BLOCK,
    
    MUSHROOM_STEM,
    
    IRON_BARS,
    
    CHAIN,
    
    GLASS_PANE,
    MELON,
    
    VINE,
    
    GLOW_LICHEN,
    
    BRICK_STAIRS,
    
    STONE_BRICK_STAIRS,
    
    MUD_BRICK_STAIRS,
    
    MYCELIUM,
    LILY_PAD,
    NETHER_BRICKS,
    CRACKED_NETHER_BRICKS,
    CHISELED_NETHER_BRICKS,
    
    NETHER_BRICK_FENCE,
    
    NETHER_BRICK_STAIRS,
    SCULK,
    
    SCULK_VEIN,
    
    SCULK_CATALYST,
    
    SCULK_SHRIEKER,
    ENCHANTING_TABLE,
    
    END_PORTAL_FRAME,
    END_STONE,
    END_STONE_BRICKS,
    DRAGON_EGG,
    
    SANDSTONE_STAIRS,
    
    ENDER_CHEST,
    EMERALD_BLOCK,
    
    OAK_STAIRS,
    
    SPRUCE_STAIRS,
    
    BIRCH_STAIRS,
    
    JUNGLE_STAIRS,
    
    ACACIA_STAIRS,
    
    CHERRY_STAIRS,
    
    DARK_OAK_STAIRS,
    
    MANGROVE_STAIRS,
    
    BAMBOO_STAIRS,
    
    BAMBOO_MOSAIC_STAIRS,
    
    CRIMSON_STAIRS,
    
    WARPED_STAIRS,
    
    COMMAND_BLOCK,
    BEACON,
    
    COBBLESTONE_WALL,
    
    MOSSY_COBBLESTONE_WALL,
    
    BRICK_WALL,
    
    PRISMARINE_WALL,
    
    RED_SANDSTONE_WALL,
    
    MOSSY_STONE_BRICK_WALL,
    
    GRANITE_WALL,
    
    STONE_BRICK_WALL,
    
    MUD_BRICK_WALL,
    
    NETHER_BRICK_WALL,
    
    ANDESITE_WALL,
    
    RED_NETHER_BRICK_WALL,
    
    SANDSTONE_WALL,
    
    END_STONE_BRICK_WALL,
    
    DIORITE_WALL,
    
    BLACKSTONE_WALL,
    
    POLISHED_BLACKSTONE_WALL,
    
    POLISHED_BLACKSTONE_BRICK_WALL,
    
    COBBLED_DEEPSLATE_WALL,
    
    POLISHED_DEEPSLATE_WALL,
    
    DEEPSLATE_BRICK_WALL,
    
    DEEPSLATE_TILE_WALL,
    
    ANVIL,
    
    CHIPPED_ANVIL,
    
    DAMAGED_ANVIL,
    CHISELED_QUARTZ_BLOCK,
    QUARTZ_BLOCK,
    QUARTZ_BRICKS,
    
    QUARTZ_PILLAR,
    
    QUARTZ_STAIRS,
    WHITE_TERRACOTTA,
    ORANGE_TERRACOTTA,
    MAGENTA_TERRACOTTA,
    LIGHT_BLUE_TERRACOTTA,
    YELLOW_TERRACOTTA,
    LIME_TERRACOTTA,
    PINK_TERRACOTTA,
    GRAY_TERRACOTTA,
    LIGHT_GRAY_TERRACOTTA,
    CYAN_TERRACOTTA,
    PURPLE_TERRACOTTA,
    BLUE_TERRACOTTA,
    BROWN_TERRACOTTA,
    GREEN_TERRACOTTA,
    RED_TERRACOTTA,
    BLACK_TERRACOTTA,
    
    BARRIER,
    
    LIGHT,
    
    HAY_BLOCK,
    WHITE_CARPET,
    ORANGE_CARPET,
    MAGENTA_CARPET,
    LIGHT_BLUE_CARPET,
    YELLOW_CARPET,
    LIME_CARPET,
    PINK_CARPET,
    GRAY_CARPET,
    LIGHT_GRAY_CARPET,
    CYAN_CARPET,
    PURPLE_CARPET,
    BLUE_CARPET,
    BROWN_CARPET,
    GREEN_CARPET,
    RED_CARPET,
    BLACK_CARPET,
    TERRACOTTA,
    PACKED_ICE,
    DIRT_PATH,
    
    SUNFLOWER,
    
    LILAC,
    
    ROSE_BUSH,
    
    PEONY,
    
    TALL_GRASS,
    
    LARGE_FERN,
    WHITE_STAINED_GLASS,
    ORANGE_STAINED_GLASS,
    MAGENTA_STAINED_GLASS,
    LIGHT_BLUE_STAINED_GLASS,
    YELLOW_STAINED_GLASS,
    LIME_STAINED_GLASS,
    PINK_STAINED_GLASS,
    GRAY_STAINED_GLASS,
    LIGHT_GRAY_STAINED_GLASS,
    CYAN_STAINED_GLASS,
    PURPLE_STAINED_GLASS,
    BLUE_STAINED_GLASS,
    BROWN_STAINED_GLASS,
    GREEN_STAINED_GLASS,
    RED_STAINED_GLASS,
    BLACK_STAINED_GLASS,
    
    WHITE_STAINED_GLASS_PANE,
    
    ORANGE_STAINED_GLASS_PANE,
    
    MAGENTA_STAINED_GLASS_PANE,
    
    LIGHT_BLUE_STAINED_GLASS_PANE,
    
    YELLOW_STAINED_GLASS_PANE,
    
    LIME_STAINED_GLASS_PANE,
    
    PINK_STAINED_GLASS_PANE,
    
    GRAY_STAINED_GLASS_PANE,
    
    LIGHT_GRAY_STAINED_GLASS_PANE,
    
    CYAN_STAINED_GLASS_PANE,
    
    PURPLE_STAINED_GLASS_PANE,
    
    BLUE_STAINED_GLASS_PANE,
    
    BROWN_STAINED_GLASS_PANE,
    
    GREEN_STAINED_GLASS_PANE,
    
    RED_STAINED_GLASS_PANE,
    
    BLACK_STAINED_GLASS_PANE,
    PRISMARINE,
    PRISMARINE_BRICKS,
    DARK_PRISMARINE,
    
    PRISMARINE_STAIRS,
    
    PRISMARINE_BRICK_STAIRS,
    
    DARK_PRISMARINE_STAIRS,
    SEA_LANTERN,
    RED_SANDSTONE,
    CHISELED_RED_SANDSTONE,
    CUT_RED_SANDSTONE,
    
    RED_SANDSTONE_STAIRS,
    
    REPEATING_COMMAND_BLOCK,
    
    CHAIN_COMMAND_BLOCK,
    MAGMA_BLOCK,
    NETHER_WART_BLOCK,
    WARPED_WART_BLOCK,
    RED_NETHER_BRICKS,
    
    BONE_BLOCK,
    STRUCTURE_VOID,
    
    SHULKER_BOX,
    
    WHITE_SHULKER_BOX,
    
    ORANGE_SHULKER_BOX,
    
    MAGENTA_SHULKER_BOX,
    
    LIGHT_BLUE_SHULKER_BOX,
    
    YELLOW_SHULKER_BOX,
    
    LIME_SHULKER_BOX,
    
    PINK_SHULKER_BOX,
    
    GRAY_SHULKER_BOX,
    
    LIGHT_GRAY_SHULKER_BOX,
    
    CYAN_SHULKER_BOX,
    
    PURPLE_SHULKER_BOX,
    
    BLUE_SHULKER_BOX,
    
    BROWN_SHULKER_BOX,
    
    GREEN_SHULKER_BOX,
    
    RED_SHULKER_BOX,
    
    BLACK_SHULKER_BOX,
    
    WHITE_GLAZED_TERRACOTTA,
    
    ORANGE_GLAZED_TERRACOTTA,
    
    MAGENTA_GLAZED_TERRACOTTA,
    
    LIGHT_BLUE_GLAZED_TERRACOTTA,
    
    YELLOW_GLAZED_TERRACOTTA,
    
    LIME_GLAZED_TERRACOTTA,
    
    PINK_GLAZED_TERRACOTTA,
    
    GRAY_GLAZED_TERRACOTTA,
    
    LIGHT_GRAY_GLAZED_TERRACOTTA,
    
    CYAN_GLAZED_TERRACOTTA,
    
    PURPLE_GLAZED_TERRACOTTA,
    
    BLUE_GLAZED_TERRACOTTA,
    
    BROWN_GLAZED_TERRACOTTA,
    
    GREEN_GLAZED_TERRACOTTA,
    
    RED_GLAZED_TERRACOTTA,
    
    BLACK_GLAZED_TERRACOTTA,
    WHITE_CONCRETE,
    ORANGE_CONCRETE,
    MAGENTA_CONCRETE,
    LIGHT_BLUE_CONCRETE,
    YELLOW_CONCRETE,
    LIME_CONCRETE,
    PINK_CONCRETE,
    GRAY_CONCRETE,
    LIGHT_GRAY_CONCRETE,
    CYAN_CONCRETE,
    PURPLE_CONCRETE,
    BLUE_CONCRETE,
    BROWN_CONCRETE,
    GREEN_CONCRETE,
    RED_CONCRETE,
    BLACK_CONCRETE,
    WHITE_CONCRETE_POWDER,
    ORANGE_CONCRETE_POWDER,
    MAGENTA_CONCRETE_POWDER,
    LIGHT_BLUE_CONCRETE_POWDER,
    YELLOW_CONCRETE_POWDER,
    LIME_CONCRETE_POWDER,
    PINK_CONCRETE_POWDER,
    GRAY_CONCRETE_POWDER,
    LIGHT_GRAY_CONCRETE_POWDER,
    CYAN_CONCRETE_POWDER,
    PURPLE_CONCRETE_POWDER,
    BLUE_CONCRETE_POWDER,
    BROWN_CONCRETE_POWDER,
    GREEN_CONCRETE_POWDER,
    RED_CONCRETE_POWDER,
    BLACK_CONCRETE_POWDER,
    
    TURTLE_EGG,
    
    SNIFFER_EGG,
    DEAD_TUBE_CORAL_BLOCK,
    DEAD_BRAIN_CORAL_BLOCK,
    DEAD_BUBBLE_CORAL_BLOCK,
    DEAD_FIRE_CORAL_BLOCK,
    DEAD_HORN_CORAL_BLOCK,
    TUBE_CORAL_BLOCK,
    BRAIN_CORAL_BLOCK,
    BUBBLE_CORAL_BLOCK,
    FIRE_CORAL_BLOCK,
    HORN_CORAL_BLOCK,
    
    TUBE_CORAL,
    
    BRAIN_CORAL,
    
    BUBBLE_CORAL,
    
    FIRE_CORAL,
    
    HORN_CORAL,
    
    DEAD_BRAIN_CORAL,
    
    DEAD_BUBBLE_CORAL,
    
    DEAD_FIRE_CORAL,
    
    DEAD_HORN_CORAL,
    
    DEAD_TUBE_CORAL,
    
    TUBE_CORAL_FAN,
    
    BRAIN_CORAL_FAN,
    
    BUBBLE_CORAL_FAN,
    
    FIRE_CORAL_FAN,
    
    HORN_CORAL_FAN,
    
    DEAD_TUBE_CORAL_FAN,
    
    DEAD_BRAIN_CORAL_FAN,
    
    DEAD_BUBBLE_CORAL_FAN,
    
    DEAD_FIRE_CORAL_FAN,
    
    DEAD_HORN_CORAL_FAN,
    BLUE_ICE,
    
    CONDUIT,
    
    POLISHED_GRANITE_STAIRS,
    
    SMOOTH_RED_SANDSTONE_STAIRS,
    
    MOSSY_STONE_BRICK_STAIRS,
    
    POLISHED_DIORITE_STAIRS,
    
    MOSSY_COBBLESTONE_STAIRS,
    
    END_STONE_BRICK_STAIRS,
    
    STONE_STAIRS,
    
    SMOOTH_SANDSTONE_STAIRS,
    
    SMOOTH_QUARTZ_STAIRS,
    
    GRANITE_STAIRS,
    
    ANDESITE_STAIRS,
    
    RED_NETHER_BRICK_STAIRS,
    
    POLISHED_ANDESITE_STAIRS,
    
    DIORITE_STAIRS,
    
    COBBLED_DEEPSLATE_STAIRS,
    
    POLISHED_DEEPSLATE_STAIRS,
    
    DEEPSLATE_BRICK_STAIRS,
    
    DEEPSLATE_TILE_STAIRS,
    
    POLISHED_GRANITE_SLAB,
    
    SMOOTH_RED_SANDSTONE_SLAB,
    
    MOSSY_STONE_BRICK_SLAB,
    
    POLISHED_DIORITE_SLAB,
    
    MOSSY_COBBLESTONE_SLAB,
    
    END_STONE_BRICK_SLAB,
    
    SMOOTH_SANDSTONE_SLAB,
    
    SMOOTH_QUARTZ_SLAB,
    
    GRANITE_SLAB,
    
    ANDESITE_SLAB,
    
    RED_NETHER_BRICK_SLAB,
    
    POLISHED_ANDESITE_SLAB,
    
    DIORITE_SLAB,
    
    COBBLED_DEEPSLATE_SLAB,
    
    POLISHED_DEEPSLATE_SLAB,
    
    DEEPSLATE_BRICK_SLAB,
    
    DEEPSLATE_TILE_SLAB,
    
    SCAFFOLDING,
    REDSTONE,
    
    REDSTONE_TORCH,
    REDSTONE_BLOCK,
    
    REPEATER,
    
    COMPARATOR,
    
    PISTON,
    
    STICKY_PISTON,
    SLIME_BLOCK,
    HONEY_BLOCK,
    
    OBSERVER,
    
    HOPPER,
    
    DISPENSER,
    
    DROPPER,
    
    LECTERN,
    
    TARGET,
    
    LEVER,
    
    LIGHTNING_ROD,
    
    DAYLIGHT_DETECTOR,
    
    SCULK_SENSOR,
    
    CALIBRATED_SCULK_SENSOR,
    
    TRIPWIRE_HOOK,
    
    TRAPPED_CHEST,
    
    TNT,
    
    REDSTONE_LAMP,
    
    NOTE_BLOCK,
    
    STONE_BUTTON,
    
    POLISHED_BLACKSTONE_BUTTON,
    
    OAK_BUTTON,
    
    SPRUCE_BUTTON,
    
    BIRCH_BUTTON,
    
    JUNGLE_BUTTON,
    
    ACACIA_BUTTON,
    
    CHERRY_BUTTON,
    
    DARK_OAK_BUTTON,
    
    MANGROVE_BUTTON,
    
    BAMBOO_BUTTON,
    
    CRIMSON_BUTTON,
    
    WARPED_BUTTON,
    
    STONE_PRESSURE_PLATE,
    
    POLISHED_BLACKSTONE_PRESSURE_PLATE,
    
    LIGHT_WEIGHTED_PRESSURE_PLATE,
    
    HEAVY_WEIGHTED_PRESSURE_PLATE,
    
    OAK_PRESSURE_PLATE,
    
    SPRUCE_PRESSURE_PLATE,
    
    BIRCH_PRESSURE_PLATE,
    
    JUNGLE_PRESSURE_PLATE,
    
    ACACIA_PRESSURE_PLATE,
    
    CHERRY_PRESSURE_PLATE,
    
    DARK_OAK_PRESSURE_PLATE,
    
    MANGROVE_PRESSURE_PLATE,
    
    BAMBOO_PRESSURE_PLATE,
    
    CRIMSON_PRESSURE_PLATE,
    
    WARPED_PRESSURE_PLATE,
    
    IRON_DOOR,
    
    OAK_DOOR,
    
    SPRUCE_DOOR,
    
    BIRCH_DOOR,
    
    JUNGLE_DOOR,
    
    ACACIA_DOOR,
    
    CHERRY_DOOR,
    
    DARK_OAK_DOOR,
    
    MANGROVE_DOOR,
    
    BAMBOO_DOOR,
    
    CRIMSON_DOOR,
    
    WARPED_DOOR,
    
    IRON_TRAPDOOR,
    
    OAK_TRAPDOOR,
    
    SPRUCE_TRAPDOOR,
    
    BIRCH_TRAPDOOR,
    
    JUNGLE_TRAPDOOR,
    
    ACACIA_TRAPDOOR,
    
    CHERRY_TRAPDOOR,
    
    DARK_OAK_TRAPDOOR,
    
    MANGROVE_TRAPDOOR,
    
    BAMBOO_TRAPDOOR,
    
    CRIMSON_TRAPDOOR,
    
    WARPED_TRAPDOOR,
    
    OAK_FENCE_GATE,
    
    SPRUCE_FENCE_GATE,
    
    BIRCH_FENCE_GATE,
    
    JUNGLE_FENCE_GATE,
    
    ACACIA_FENCE_GATE,
    
    CHERRY_FENCE_GATE,
    
    DARK_OAK_FENCE_GATE,
    
    MANGROVE_FENCE_GATE,
    
    BAMBOO_FENCE_GATE,
    
    CRIMSON_FENCE_GATE,
    
    WARPED_FENCE_GATE,
    
    POWERED_RAIL,
    
    DETECTOR_RAIL,
    
    RAIL,
    
    ACTIVATOR_RAIL,
    SADDLE,
    MINECART,
    CHEST_MINECART,
    FURNACE_MINECART,
    TNT_MINECART,
    HOPPER_MINECART,
    CARROT_ON_A_STICK,
    WARPED_FUNGUS_ON_A_STICK,
    ELYTRA,
    OAK_BOAT,
    OAK_CHEST_BOAT,
    SPRUCE_BOAT,
    SPRUCE_CHEST_BOAT,
    BIRCH_BOAT,
    BIRCH_CHEST_BOAT,
    JUNGLE_BOAT,
    JUNGLE_CHEST_BOAT,
    ACACIA_BOAT,
    ACACIA_CHEST_BOAT,
    CHERRY_BOAT,
    CHERRY_CHEST_BOAT,
    DARK_OAK_BOAT,
    DARK_OAK_CHEST_BOAT,
    MANGROVE_BOAT,
    MANGROVE_CHEST_BOAT,
    BAMBOO_RAFT,
    BAMBOO_CHEST_RAFT,
    
    STRUCTURE_BLOCK,
    
    JIGSAW,
    TURTLE_HELMET,
    SCUTE,
    FLINT_AND_STEEL,
    APPLE,
    BOW,
    ARROW,
    COAL,
    CHARCOAL,
    DIAMOND,
    EMERALD,
    LAPIS_LAZULI,
    QUARTZ,
    AMETHYST_SHARD,
    RAW_IRON,
    IRON_INGOT,
    RAW_COPPER,
    COPPER_INGOT,
    RAW_GOLD,
    GOLD_INGOT,
    NETHERITE_INGOT,
    NETHERITE_SCRAP,
    WOODEN_SWORD,
    WOODEN_SHOVEL,
    WOODEN_PICKAXE,
    WOODEN_AXE,
    WOODEN_HOE,
    STONE_SWORD,
    STONE_SHOVEL,
    STONE_PICKAXE,
    STONE_AXE,
    STONE_HOE,
    GOLDEN_SWORD,
    GOLDEN_SHOVEL,
    GOLDEN_PICKAXE,
    GOLDEN_AXE,
    GOLDEN_HOE,
    IRON_SWORD,
    IRON_SHOVEL,
    IRON_PICKAXE,
    IRON_AXE,
    IRON_HOE,
    DIAMOND_SWORD,
    DIAMOND_SHOVEL,
    DIAMOND_PICKAXE,
    DIAMOND_AXE,
    DIAMOND_HOE,
    NETHERITE_SWORD,
    NETHERITE_SHOVEL,
    NETHERITE_PICKAXE,
    NETHERITE_AXE,
    NETHERITE_HOE,
    STICK,
    BOWL,
    MUSHROOM_STEW,
    STRING,
    FEATHER,
    GUNPOWDER,
    WHEAT_SEEDS,
    
    WHEAT,
    BREAD,
    LEATHER_HELMET,
    LEATHER_CHESTPLATE,
    LEATHER_LEGGINGS,
    LEATHER_BOOTS,
    CHAINMAIL_HELMET,
    CHAINMAIL_CHESTPLATE,
    CHAINMAIL_LEGGINGS,
    CHAINMAIL_BOOTS,
    IRON_HELMET,
    IRON_CHESTPLATE,
    IRON_LEGGINGS,
    IRON_BOOTS,
    DIAMOND_HELMET,
    DIAMOND_CHESTPLATE,
    DIAMOND_LEGGINGS,
    DIAMOND_BOOTS,
    GOLDEN_HELMET,
    GOLDEN_CHESTPLATE,
    GOLDEN_LEGGINGS,
    GOLDEN_BOOTS,
    NETHERITE_HELMET,
    NETHERITE_CHESTPLATE,
    NETHERITE_LEGGINGS,
    NETHERITE_BOOTS,
    FLINT,
    PORKCHOP,
    COOKED_PORKCHOP,
    PAINTING,
    GOLDEN_APPLE,
    ENCHANTED_GOLDEN_APPLE,
    
    OAK_SIGN,
    
    SPRUCE_SIGN,
    
    BIRCH_SIGN,
    
    JUNGLE_SIGN,
    
    ACACIA_SIGN,
    
    CHERRY_SIGN,
    
    DARK_OAK_SIGN,
    
    MANGROVE_SIGN,
    
    BAMBOO_SIGN,
    
    CRIMSON_SIGN,
    
    WARPED_SIGN,
    
    OAK_HANGING_SIGN,
    
    SPRUCE_HANGING_SIGN,
    
    BIRCH_HANGING_SIGN,
    
    JUNGLE_HANGING_SIGN,
    
    ACACIA_HANGING_SIGN,
    
    CHERRY_HANGING_SIGN,
    
    DARK_OAK_HANGING_SIGN,
    
    MANGROVE_HANGING_SIGN,
    
    BAMBOO_HANGING_SIGN,
    
    CRIMSON_HANGING_SIGN,
    
    WARPED_HANGING_SIGN,
    BUCKET,
    WATER_BUCKET,
    LAVA_BUCKET,
    POWDER_SNOW_BUCKET,
    SNOWBALL,
    LEATHER,
    MILK_BUCKET,
    PUFFERFISH_BUCKET,
    SALMON_BUCKET,
    COD_BUCKET,
    TROPICAL_FISH_BUCKET,
    AXOLOTL_BUCKET,
    TADPOLE_BUCKET,
    BRICK,
    CLAY_BALL,
    DRIED_KELP_BLOCK,
    PAPER,
    BOOK,
    SLIME_BALL,
    EGG,
    COMPASS,
    RECOVERY_COMPASS,
    BUNDLE,
    FISHING_ROD,
    CLOCK,
    SPYGLASS,
    GLOWSTONE_DUST,
    COD,
    SALMON,
    TROPICAL_FISH,
    PUFFERFISH,
    COOKED_COD,
    COOKED_SALMON,
    INK_SAC,
    GLOW_INK_SAC,
    COCOA_BEANS,
    WHITE_DYE,
    ORANGE_DYE,
    MAGENTA_DYE,
    LIGHT_BLUE_DYE,
    YELLOW_DYE,
    LIME_DYE,
    PINK_DYE,
    GRAY_DYE,
    LIGHT_GRAY_DYE,
    CYAN_DYE,
    PURPLE_DYE,
    BLUE_DYE,
    BROWN_DYE,
    GREEN_DYE,
    RED_DYE,
    BLACK_DYE,
    BONE_MEAL,
    BONE,
    SUGAR,
    
    CAKE,
    
    WHITE_BED,
    
    ORANGE_BED,
    
    MAGENTA_BED,
    
    LIGHT_BLUE_BED,
    
    YELLOW_BED,
    
    LIME_BED,
    
    PINK_BED,
    
    GRAY_BED,
    
    LIGHT_GRAY_BED,
    
    CYAN_BED,
    
    PURPLE_BED,
    
    BLUE_BED,
    
    BROWN_BED,
    
    GREEN_BED,
    
    RED_BED,
    
    BLACK_BED,
    COOKIE,
    FILLED_MAP,
    SHEARS,
    MELON_SLICE,
    DRIED_KELP,
    PUMPKIN_SEEDS,
    MELON_SEEDS,
    BEEF,
    COOKED_BEEF,
    CHICKEN,
    COOKED_CHICKEN,
    ROTTEN_FLESH,
    ENDER_PEARL,
    BLAZE_ROD,
    GHAST_TEAR,
    GOLD_NUGGET,
    
    NETHER_WART,
    POTION,
    GLASS_BOTTLE,
    SPIDER_EYE,
    FERMENTED_SPIDER_EYE,
    BLAZE_POWDER,
    MAGMA_CREAM,
    
    BREWING_STAND,
    CAULDRON,
    ENDER_EYE,
    GLISTERING_MELON_SLICE,
    ALLAY_SPAWN_EGG,
    AXOLOTL_SPAWN_EGG,
    BAT_SPAWN_EGG,
    BEE_SPAWN_EGG,
    BLAZE_SPAWN_EGG,
    CAT_SPAWN_EGG,
    CAMEL_SPAWN_EGG,
    CAVE_SPIDER_SPAWN_EGG,
    CHICKEN_SPAWN_EGG,
    COD_SPAWN_EGG,
    COW_SPAWN_EGG,
    CREEPER_SPAWN_EGG,
    DOLPHIN_SPAWN_EGG,
    DONKEY_SPAWN_EGG,
    DROWNED_SPAWN_EGG,
    ELDER_GUARDIAN_SPAWN_EGG,
    ENDER_DRAGON_SPAWN_EGG,
    ENDERMAN_SPAWN_EGG,
    ENDERMITE_SPAWN_EGG,
    EVOKER_SPAWN_EGG,
    FOX_SPAWN_EGG,
    FROG_SPAWN_EGG,
    GHAST_SPAWN_EGG,
    GLOW_SQUID_SPAWN_EGG,
    GOAT_SPAWN_EGG,
    GUARDIAN_SPAWN_EGG,
    HOGLIN_SPAWN_EGG,
    HORSE_SPAWN_EGG,
    HUSK_SPAWN_EGG,
    IRON_GOLEM_SPAWN_EGG,
    LLAMA_SPAWN_EGG,
    MAGMA_CUBE_SPAWN_EGG,
    MOOSHROOM_SPAWN_EGG,
    MULE_SPAWN_EGG,
    OCELOT_SPAWN_EGG,
    PANDA_SPAWN_EGG,
    PARROT_SPAWN_EGG,
    PHANTOM_SPAWN_EGG,
    PIG_SPAWN_EGG,
    PIGLIN_SPAWN_EGG,
    PIGLIN_BRUTE_SPAWN_EGG,
    PILLAGER_SPAWN_EGG,
    POLAR_BEAR_SPAWN_EGG,
    PUFFERFISH_SPAWN_EGG,
    RABBIT_SPAWN_EGG,
    RAVAGER_SPAWN_EGG,
    SALMON_SPAWN_EGG,
    SHEEP_SPAWN_EGG,
    SHULKER_SPAWN_EGG,
    SILVERFISH_SPAWN_EGG,
    SKELETON_SPAWN_EGG,
    SKELETON_HORSE_SPAWN_EGG,
    SLIME_SPAWN_EGG,
    SNIFFER_SPAWN_EGG,
    SNOW_GOLEM_SPAWN_EGG,
    SPIDER_SPAWN_EGG,
    SQUID_SPAWN_EGG,
    STRAY_SPAWN_EGG,
    STRIDER_SPAWN_EGG,
    TADPOLE_SPAWN_EGG,
    TRADER_LLAMA_SPAWN_EGG,
    TROPICAL_FISH_SPAWN_EGG,
    TURTLE_SPAWN_EGG,
    VEX_SPAWN_EGG,
    VILLAGER_SPAWN_EGG,
    VINDICATOR_SPAWN_EGG,
    WANDERING_TRADER_SPAWN_EGG,
    WARDEN_SPAWN_EGG,
    WITCH_SPAWN_EGG,
    WITHER_SPAWN_EGG,
    WITHER_SKELETON_SPAWN_EGG,
    WOLF_SPAWN_EGG,
    ZOGLIN_SPAWN_EGG,
    ZOMBIE_SPAWN_EGG,
    ZOMBIE_HORSE_SPAWN_EGG,
    ZOMBIE_VILLAGER_SPAWN_EGG,
    ZOMBIFIED_PIGLIN_SPAWN_EGG,
    EXPERIENCE_BOTTLE,
    FIRE_CHARGE,
    WRITABLE_BOOK,
    WRITTEN_BOOK,
    ITEM_FRAME,
    GLOW_ITEM_FRAME,
    FLOWER_POT,
    CARROT,
    POTATO,
    BAKED_POTATO,
    POISONOUS_POTATO,
    MAP,
    GOLDEN_CARROT,
    
    SKELETON_SKULL,
    
    WITHER_SKELETON_SKULL,
    
    PLAYER_HEAD,
    
    ZOMBIE_HEAD,
    
    CREEPER_HEAD,
    
    DRAGON_HEAD,
    
    PIGLIN_HEAD,
    NETHER_STAR,
    PUMPKIN_PIE,
    FIREWORK_ROCKET,
    FIREWORK_STAR,
    ENCHANTED_BOOK,
    NETHER_BRICK,
    PRISMARINE_SHARD,
    PRISMARINE_CRYSTALS,
    RABBIT,
    COOKED_RABBIT,
    RABBIT_STEW,
    RABBIT_FOOT,
    RABBIT_HIDE,
    ARMOR_STAND,
    IRON_HORSE_ARMOR,
    GOLDEN_HORSE_ARMOR,
    DIAMOND_HORSE_ARMOR,
    LEATHER_HORSE_ARMOR,
    LEAD,
    NAME_TAG,
    COMMAND_BLOCK_MINECART,
    MUTTON,
    COOKED_MUTTON,
    
    WHITE_BANNER,
    
    ORANGE_BANNER,
    
    MAGENTA_BANNER,
    
    LIGHT_BLUE_BANNER,
    
    YELLOW_BANNER,
    
    LIME_BANNER,
    
    PINK_BANNER,
    
    GRAY_BANNER,
    
    LIGHT_GRAY_BANNER,
    
    CYAN_BANNER,
    
    PURPLE_BANNER,
    
    BLUE_BANNER,
    
    BROWN_BANNER,
    
    GREEN_BANNER,
    
    RED_BANNER,
    
    BLACK_BANNER,
    END_CRYSTAL,
    CHORUS_FRUIT,
    POPPED_CHORUS_FRUIT,
    TORCHFLOWER_SEEDS,
    PITCHER_POD,
    BEETROOT,
    BEETROOT_SEEDS,
    BEETROOT_SOUP,
    DRAGON_BREATH,
    SPLASH_POTION,
    SPECTRAL_ARROW,
    TIPPED_ARROW,
    LINGERING_POTION,
    SHIELD,
    TOTEM_OF_UNDYING,
    SHULKER_SHELL,
    IRON_NUGGET,
    KNOWLEDGE_BOOK,
    DEBUG_STICK,
    MUSIC_DISC_13,
    MUSIC_DISC_CAT,
    MUSIC_DISC_BLOCKS,
    MUSIC_DISC_CHIRP,
    MUSIC_DISC_FAR,
    MUSIC_DISC_MALL,
    MUSIC_DISC_MELLOHI,
    MUSIC_DISC_STAL,
    MUSIC_DISC_STRAD,
    MUSIC_DISC_WARD,
    MUSIC_DISC_11,
    MUSIC_DISC_WAIT,
    MUSIC_DISC_OTHERSIDE,
    MUSIC_DISC_RELIC,
    MUSIC_DISC_5,
    MUSIC_DISC_PIGSTEP,
    DISC_FRAGMENT_5,
    TRIDENT,
    PHANTOM_MEMBRANE,
    NAUTILUS_SHELL,
    HEART_OF_THE_SEA,
    CROSSBOW,
    SUSPICIOUS_STEW,
    
    LOOM,
    FLOWER_BANNER_PATTERN,
    CREEPER_BANNER_PATTERN,
    SKULL_BANNER_PATTERN,
    MOJANG_BANNER_PATTERN,
    GLOBE_BANNER_PATTERN,
    PIGLIN_BANNER_PATTERN,
    GOAT_HORN,
    
    COMPOSTER,
    
    BARREL,
    
    SMOKER,
    
    BLAST_FURNACE,
    CARTOGRAPHY_TABLE,
    FLETCHING_TABLE,
    
    GRINDSTONE,
    SMITHING_TABLE,
    
    STONECUTTER,
    
    BELL,
    
    LANTERN,
    
    SOUL_LANTERN,
    SWEET_BERRIES,
    GLOW_BERRIES,
    
    CAMPFIRE,
    
    SOUL_CAMPFIRE,
    SHROOMLIGHT,
    HONEYCOMB,
    
    BEE_NEST,
    
    BEEHIVE,
    HONEY_BOTTLE,
    HONEYCOMB_BLOCK,
    LODESTONE,
    CRYING_OBSIDIAN,
    BLACKSTONE,
    
    BLACKSTONE_SLAB,
    
    BLACKSTONE_STAIRS,
    GILDED_BLACKSTONE,
    POLISHED_BLACKSTONE,
    
    POLISHED_BLACKSTONE_SLAB,
    
    POLISHED_BLACKSTONE_STAIRS,
    CHISELED_POLISHED_BLACKSTONE,
    POLISHED_BLACKSTONE_BRICKS,
    
    POLISHED_BLACKSTONE_BRICK_SLAB,
    
    POLISHED_BLACKSTONE_BRICK_STAIRS,
    CRACKED_POLISHED_BLACKSTONE_BRICKS,
    
    RESPAWN_ANCHOR,
    
    CANDLE,
    
    WHITE_CANDLE,
    
    ORANGE_CANDLE,
    
    MAGENTA_CANDLE,
    
    LIGHT_BLUE_CANDLE,
    
    YELLOW_CANDLE,
    
    LIME_CANDLE,
    
    PINK_CANDLE,
    
    GRAY_CANDLE,
    
    LIGHT_GRAY_CANDLE,
    
    CYAN_CANDLE,
    
    PURPLE_CANDLE,
    
    BLUE_CANDLE,
    
    BROWN_CANDLE,
    
    GREEN_CANDLE,
    
    RED_CANDLE,
    
    BLACK_CANDLE,
    
    SMALL_AMETHYST_BUD,
    
    MEDIUM_AMETHYST_BUD,
    
    LARGE_AMETHYST_BUD,
    
    AMETHYST_CLUSTER,
    
    POINTED_DRIPSTONE,
    
    OCHRE_FROGLIGHT,
    
    VERDANT_FROGLIGHT,
    
    PEARLESCENT_FROGLIGHT,
    FROGSPAWN,
    ECHO_SHARD,
    BRUSH,
    NETHERITE_UPGRADE_SMITHING_TEMPLATE,
    SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE,
    DUNE_ARMOR_TRIM_SMITHING_TEMPLATE,
    COAST_ARMOR_TRIM_SMITHING_TEMPLATE,
    WILD_ARMOR_TRIM_SMITHING_TEMPLATE,
    WARD_ARMOR_TRIM_SMITHING_TEMPLATE,
    EYE_ARMOR_TRIM_SMITHING_TEMPLATE,
    VEX_ARMOR_TRIM_SMITHING_TEMPLATE,
    TIDE_ARMOR_TRIM_SMITHING_TEMPLATE,
    SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE,
    RIB_ARMOR_TRIM_SMITHING_TEMPLATE,
    SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE,
    WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE,
    SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE,
    SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE,
    RAISER_ARMOR_TRIM_SMITHING_TEMPLATE,
    HOST_ARMOR_TRIM_SMITHING_TEMPLATE,
    ANGLER_POTTERY_SHERD,
    ARCHER_POTTERY_SHERD,
    ARMS_UP_POTTERY_SHERD,
    BLADE_POTTERY_SHERD,
    BREWER_POTTERY_SHERD,
    BURN_POTTERY_SHERD,
    DANGER_POTTERY_SHERD,
    EXPLORER_POTTERY_SHERD,
    FRIEND_POTTERY_SHERD,
    HEART_POTTERY_SHERD,
    HEARTBREAK_POTTERY_SHERD,
    HOWL_POTTERY_SHERD,
    MINER_POTTERY_SHERD,
    MOURNER_POTTERY_SHERD,
    PLENTY_POTTERY_SHERD,
    PRIZE_POTTERY_SHERD,
    SHEAF_POTTERY_SHERD,
    SHELTER_POTTERY_SHERD,
    SKULL_POTTERY_SHERD,
    SNORT_POTTERY_SHERD,
    
    WATER,
    
    LAVA,
    
    TALL_SEAGRASS,
    
    PISTON_HEAD,
    
    MOVING_PISTON,
    
    WALL_TORCH,
    
    FIRE,
    SOUL_FIRE,
    
    REDSTONE_WIRE,
    
    OAK_WALL_SIGN,
    
    SPRUCE_WALL_SIGN,
    
    BIRCH_WALL_SIGN,
    
    ACACIA_WALL_SIGN,
    
    CHERRY_WALL_SIGN,
    
    JUNGLE_WALL_SIGN,
    
    DARK_OAK_WALL_SIGN,
    
    MANGROVE_WALL_SIGN,
    
    BAMBOO_WALL_SIGN,
    
    OAK_WALL_HANGING_SIGN,
    
    SPRUCE_WALL_HANGING_SIGN,
    
    BIRCH_WALL_HANGING_SIGN,
    
    ACACIA_WALL_HANGING_SIGN,
    
    CHERRY_WALL_HANGING_SIGN,
    
    JUNGLE_WALL_HANGING_SIGN,
    
    DARK_OAK_WALL_HANGING_SIGN,
    
    MANGROVE_WALL_HANGING_SIGN,
    
    CRIMSON_WALL_HANGING_SIGN,
    
    WARPED_WALL_HANGING_SIGN,
    
    BAMBOO_WALL_HANGING_SIGN,
    
    REDSTONE_WALL_TORCH,
    
    SOUL_WALL_TORCH,
    
    NETHER_PORTAL,
    
    ATTACHED_PUMPKIN_STEM,
    
    ATTACHED_MELON_STEM,
    
    PUMPKIN_STEM,
    
    MELON_STEM,
    
    WATER_CAULDRON,
    LAVA_CAULDRON,
    
    POWDER_SNOW_CAULDRON,
    END_PORTAL,
    
    COCOA,
    
    TRIPWIRE,
    POTTED_TORCHFLOWER,
    POTTED_OAK_SAPLING,
    POTTED_SPRUCE_SAPLING,
    POTTED_BIRCH_SAPLING,
    POTTED_JUNGLE_SAPLING,
    POTTED_ACACIA_SAPLING,
    POTTED_CHERRY_SAPLING,
    POTTED_DARK_OAK_SAPLING,
    POTTED_MANGROVE_PROPAGULE,
    POTTED_FERN,
    POTTED_DANDELION,
    POTTED_POPPY,
    POTTED_BLUE_ORCHID,
    POTTED_ALLIUM,
    POTTED_AZURE_BLUET,
    POTTED_RED_TULIP,
    POTTED_ORANGE_TULIP,
    POTTED_WHITE_TULIP,
    POTTED_PINK_TULIP,
    POTTED_OXEYE_DAISY,
    POTTED_CORNFLOWER,
    POTTED_LILY_OF_THE_VALLEY,
    POTTED_WITHER_ROSE,
    POTTED_RED_MUSHROOM,
    POTTED_BROWN_MUSHROOM,
    POTTED_DEAD_BUSH,
    POTTED_CACTUS,
    
    CARROTS,
    
    POTATOES,
    
    SKELETON_WALL_SKULL,
    
    WITHER_SKELETON_WALL_SKULL,
    
    ZOMBIE_WALL_HEAD,
    
    PLAYER_WALL_HEAD,
    
    CREEPER_WALL_HEAD,
    
    DRAGON_WALL_HEAD,
    
    PIGLIN_WALL_HEAD,
    
    WHITE_WALL_BANNER,
    
    ORANGE_WALL_BANNER,
    
    MAGENTA_WALL_BANNER,
    
    LIGHT_BLUE_WALL_BANNER,
    
    YELLOW_WALL_BANNER,
    
    LIME_WALL_BANNER,
    
    PINK_WALL_BANNER,
    
    GRAY_WALL_BANNER,
    
    LIGHT_GRAY_WALL_BANNER,
    
    CYAN_WALL_BANNER,
    
    PURPLE_WALL_BANNER,
    
    BLUE_WALL_BANNER,
    
    BROWN_WALL_BANNER,
    
    GREEN_WALL_BANNER,
    
    RED_WALL_BANNER,
    
    BLACK_WALL_BANNER,
    
    TORCHFLOWER_CROP,
    
    PITCHER_CROP,
    
    BEETROOTS,
    END_GATEWAY,
    
    FROSTED_ICE,
    KELP_PLANT,
    
    DEAD_TUBE_CORAL_WALL_FAN,
    
    DEAD_BRAIN_CORAL_WALL_FAN,
    
    DEAD_BUBBLE_CORAL_WALL_FAN,
    
    DEAD_FIRE_CORAL_WALL_FAN,
    
    DEAD_HORN_CORAL_WALL_FAN,
    
    TUBE_CORAL_WALL_FAN,
    
    BRAIN_CORAL_WALL_FAN,
    
    BUBBLE_CORAL_WALL_FAN,
    
    FIRE_CORAL_WALL_FAN,
    
    HORN_CORAL_WALL_FAN,
    BAMBOO_SAPLING,
    POTTED_BAMBOO,
    VOID_AIR,
    CAVE_AIR,
    
    BUBBLE_COLUMN,
    
    SWEET_BERRY_BUSH,
    WEEPING_VINES_PLANT,
    TWISTING_VINES_PLANT,
    
    CRIMSON_WALL_SIGN,
    
    WARPED_WALL_SIGN,
    POTTED_CRIMSON_FUNGUS,
    POTTED_WARPED_FUNGUS,
    POTTED_CRIMSON_ROOTS,
    POTTED_WARPED_ROOTS,
    
    CANDLE_CAKE,
    
    WHITE_CANDLE_CAKE,
    
    ORANGE_CANDLE_CAKE,
    
    MAGENTA_CANDLE_CAKE,
    
    LIGHT_BLUE_CANDLE_CAKE,
    
    YELLOW_CANDLE_CAKE,
    
    LIME_CANDLE_CAKE,
    
    PINK_CANDLE_CAKE,
    
    GRAY_CANDLE_CAKE,
    
    LIGHT_GRAY_CANDLE_CAKE,
    
    CYAN_CANDLE_CAKE,
    
    PURPLE_CANDLE_CAKE,
    
    BLUE_CANDLE_CAKE,
    
    BROWN_CANDLE_CAKE,
    
    GREEN_CANDLE_CAKE,
    
    RED_CANDLE_CAKE,
    
    BLACK_CANDLE_CAKE,
    POWDER_SNOW,
    
    CAVE_VINES,
    
    CAVE_VINES_PLANT,
    
    BIG_DRIPLEAF_STEM,
    POTTED_AZALEA_BUSH,
    POTTED_FLOWERING_AZALEA_BUSH,

    ;


    private Material() {
     
    }

 


    
    public boolean isBlock() {
        switch (this) {
            case ACACIA_BUTTON:
            case ACACIA_DOOR:
            case ACACIA_FENCE:
            case ACACIA_FENCE_GATE:
            case ACACIA_HANGING_SIGN:
            case ACACIA_LEAVES:
            case ACACIA_LOG:
            case ACACIA_PLANKS:
            case ACACIA_PRESSURE_PLATE:
            case ACACIA_SAPLING:
            case ACACIA_SIGN:
            case ACACIA_SLAB:
            case ACACIA_STAIRS:
            case ACACIA_TRAPDOOR:
            case ACACIA_WALL_HANGING_SIGN:
            case ACACIA_WALL_SIGN:
            case ACACIA_WOOD:
            case ACTIVATOR_RAIL:
            case AIR:
            case ALLIUM:
            case AMETHYST_BLOCK:
            case AMETHYST_CLUSTER:
            case ANCIENT_DEBRIS:
            case ANDESITE:
            case ANDESITE_SLAB:
            case ANDESITE_STAIRS:
            case ANDESITE_WALL:
            case ANVIL:
            case ATTACHED_MELON_STEM:
            case ATTACHED_PUMPKIN_STEM:
            case AZALEA:
            case AZALEA_LEAVES:
            case AZURE_BLUET:
            case BAMBOO:
            case BAMBOO_BLOCK:
            case BAMBOO_BUTTON:
            case BAMBOO_DOOR:
            case BAMBOO_FENCE:
            case BAMBOO_FENCE_GATE:
            case BAMBOO_HANGING_SIGN:
            case BAMBOO_MOSAIC:
            case BAMBOO_MOSAIC_SLAB:
            case BAMBOO_MOSAIC_STAIRS:
            case BAMBOO_PLANKS:
            case BAMBOO_PRESSURE_PLATE:
            case BAMBOO_SAPLING:
            case BAMBOO_SIGN:
            case BAMBOO_SLAB:
            case BAMBOO_STAIRS:
            case BAMBOO_TRAPDOOR:
            case BAMBOO_WALL_HANGING_SIGN:
            case BAMBOO_WALL_SIGN:
            case BARREL:
            case BARRIER:
            case BASALT:
            case BEACON:
            case BEDROCK:
            case BEEHIVE:
            case BEETROOTS:
            case BEE_NEST:
            case BELL:
            case BIG_DRIPLEAF:
            case BIG_DRIPLEAF_STEM:
            case BIRCH_BUTTON:
            case BIRCH_DOOR:
            case BIRCH_FENCE:
            case BIRCH_FENCE_GATE:
            case BIRCH_HANGING_SIGN:
            case BIRCH_LEAVES:
            case BIRCH_LOG:
            case BIRCH_PLANKS:
            case BIRCH_PRESSURE_PLATE:
            case BIRCH_SAPLING:
            case BIRCH_SIGN:
            case BIRCH_SLAB:
            case BIRCH_STAIRS:
            case BIRCH_TRAPDOOR:
            case BIRCH_WALL_HANGING_SIGN:
            case BIRCH_WALL_SIGN:
            case BIRCH_WOOD:
            case BLACKSTONE:
            case BLACKSTONE_SLAB:
            case BLACKSTONE_STAIRS:
            case BLACKSTONE_WALL:
            case BLACK_BANNER:
            case BLACK_BED:
            case BLACK_CANDLE:
            case BLACK_CANDLE_CAKE:
            case BLACK_CARPET:
            case BLACK_CONCRETE:
            case BLACK_CONCRETE_POWDER:
            case BLACK_GLAZED_TERRACOTTA:
            case BLACK_SHULKER_BOX:
            case BLACK_STAINED_GLASS:
            case BLACK_STAINED_GLASS_PANE:
            case BLACK_TERRACOTTA:
            case BLACK_WALL_BANNER:
            case BLACK_WOOL:
            case BLAST_FURNACE:
            case BLUE_BANNER:
            case BLUE_BED:
            case BLUE_CANDLE:
            case BLUE_CANDLE_CAKE:
            case BLUE_CARPET:
            case BLUE_CONCRETE:
            case BLUE_CONCRETE_POWDER:
            case BLUE_GLAZED_TERRACOTTA:
            case BLUE_ICE:
            case BLUE_ORCHID:
            case BLUE_SHULKER_BOX:
            case BLUE_STAINED_GLASS:
            case BLUE_STAINED_GLASS_PANE:
            case BLUE_TERRACOTTA:
            case BLUE_WALL_BANNER:
            case BLUE_WOOL:
            case BONE_BLOCK:
            case BOOKSHELF:
            case BRAIN_CORAL:
            case BRAIN_CORAL_BLOCK:
            case BRAIN_CORAL_FAN:
            case BRAIN_CORAL_WALL_FAN:
            case BREWING_STAND:
            case BRICKS:
            case BRICK_SLAB:
            case BRICK_STAIRS:
            case BRICK_WALL:
            case BROWN_BANNER:
            case BROWN_BED:
            case BROWN_CANDLE:
            case BROWN_CANDLE_CAKE:
            case BROWN_CARPET:
            case BROWN_CONCRETE:
            case BROWN_CONCRETE_POWDER:
            case BROWN_GLAZED_TERRACOTTA:
            case BROWN_MUSHROOM:
            case BROWN_MUSHROOM_BLOCK:
            case BROWN_SHULKER_BOX:
            case BROWN_STAINED_GLASS:
            case BROWN_STAINED_GLASS_PANE:
            case BROWN_TERRACOTTA:
            case BROWN_WALL_BANNER:
            case BROWN_WOOL:
            case BUBBLE_COLUMN:
            case BUBBLE_CORAL:
            case BUBBLE_CORAL_BLOCK:
            case BUBBLE_CORAL_FAN:
            case BUBBLE_CORAL_WALL_FAN:
            case BUDDING_AMETHYST:
            case CACTUS:
            case CAKE:
            case CALCITE:
            case CALIBRATED_SCULK_SENSOR:
            case CAMPFIRE:
            case CANDLE:
            case CANDLE_CAKE:
            case CARROTS:
            case CARTOGRAPHY_TABLE:
            case CARVED_PUMPKIN:
            case CAULDRON:
            case CAVE_AIR:
            case CAVE_VINES:
            case CAVE_VINES_PLANT:
            case CHAIN:
            case CHAIN_COMMAND_BLOCK:
            case CHERRY_BUTTON:
            case CHERRY_DOOR:
            case CHERRY_FENCE:
            case CHERRY_FENCE_GATE:
            case CHERRY_HANGING_SIGN:
            case CHERRY_LEAVES:
            case CHERRY_LOG:
            case CHERRY_PLANKS:
            case CHERRY_PRESSURE_PLATE:
            case CHERRY_SAPLING:
            case CHERRY_SIGN:
            case CHERRY_SLAB:
            case CHERRY_STAIRS:
            case CHERRY_TRAPDOOR:
            case CHERRY_WALL_HANGING_SIGN:
            case CHERRY_WALL_SIGN:
            case CHERRY_WOOD:
            case CHEST:
            case CHIPPED_ANVIL:
            case CHISELED_BOOKSHELF:
            case CHISELED_DEEPSLATE:
            case CHISELED_NETHER_BRICKS:
            case CHISELED_POLISHED_BLACKSTONE:
            case CHISELED_QUARTZ_BLOCK:
            case CHISELED_RED_SANDSTONE:
            case CHISELED_SANDSTONE:
            case CHISELED_STONE_BRICKS:
            case CHORUS_FLOWER:
            case CHORUS_PLANT:
            case CLAY:
            case COAL_BLOCK:
            case COAL_ORE:
            case COARSE_DIRT:
            case COBBLED_DEEPSLATE:
            case COBBLED_DEEPSLATE_SLAB:
            case COBBLED_DEEPSLATE_STAIRS:
            case COBBLED_DEEPSLATE_WALL:
            case COBBLESTONE:
            case COBBLESTONE_SLAB:
            case COBBLESTONE_STAIRS:
            case COBBLESTONE_WALL:
            case COBWEB:
            case COCOA:
            case COMMAND_BLOCK:
            case COMPARATOR:
            case COMPOSTER:
            case CONDUIT:
            case COPPER_BLOCK:
            case COPPER_ORE:
            case CORNFLOWER:
            case CRACKED_DEEPSLATE_BRICKS:
            case CRACKED_DEEPSLATE_TILES:
            case CRACKED_NETHER_BRICKS:
            case CRACKED_POLISHED_BLACKSTONE_BRICKS:
            case CRACKED_STONE_BRICKS:
            case CRAFTING_TABLE:
            case CREEPER_HEAD:
            case CREEPER_WALL_HEAD:
            case CRIMSON_BUTTON:
            case CRIMSON_DOOR:
            case CRIMSON_FENCE:
            case CRIMSON_FENCE_GATE:
            case CRIMSON_FUNGUS:
            case CRIMSON_HANGING_SIGN:
            case CRIMSON_HYPHAE:
            case CRIMSON_NYLIUM:
            case CRIMSON_PLANKS:
            case CRIMSON_PRESSURE_PLATE:
            case CRIMSON_ROOTS:
            case CRIMSON_SIGN:
            case CRIMSON_SLAB:
            case CRIMSON_STAIRS:
            case CRIMSON_STEM:
            case CRIMSON_TRAPDOOR:
            case CRIMSON_WALL_HANGING_SIGN:
            case CRIMSON_WALL_SIGN:
            case CRYING_OBSIDIAN:
            case CUT_COPPER:
            case CUT_COPPER_SLAB:
            case CUT_COPPER_STAIRS:
            case CUT_RED_SANDSTONE:
            case CUT_RED_SANDSTONE_SLAB:
            case CUT_SANDSTONE:
            case CUT_SANDSTONE_SLAB:
            case CYAN_BANNER:
            case CYAN_BED:
            case CYAN_CANDLE:
            case CYAN_CANDLE_CAKE:
            case CYAN_CARPET:
            case CYAN_CONCRETE:
            case CYAN_CONCRETE_POWDER:
            case CYAN_GLAZED_TERRACOTTA:
            case CYAN_SHULKER_BOX:
            case CYAN_STAINED_GLASS:
            case CYAN_STAINED_GLASS_PANE:
            case CYAN_TERRACOTTA:
            case CYAN_WALL_BANNER:
            case CYAN_WOOL:
            case DAMAGED_ANVIL:
            case DANDELION:
            case DARK_OAK_BUTTON:
            case DARK_OAK_DOOR:
            case DARK_OAK_FENCE:
            case DARK_OAK_FENCE_GATE:
            case DARK_OAK_HANGING_SIGN:
            case DARK_OAK_LEAVES:
            case DARK_OAK_LOG:
            case DARK_OAK_PLANKS:
            case DARK_OAK_PRESSURE_PLATE:
            case DARK_OAK_SAPLING:
            case DARK_OAK_SIGN:
            case DARK_OAK_SLAB:
            case DARK_OAK_STAIRS:
            case DARK_OAK_TRAPDOOR:
            case DARK_OAK_WALL_HANGING_SIGN:
            case DARK_OAK_WALL_SIGN:
            case DARK_OAK_WOOD:
            case DARK_PRISMARINE:
            case DARK_PRISMARINE_SLAB:
            case DARK_PRISMARINE_STAIRS:
            case DAYLIGHT_DETECTOR:
            case DEAD_BRAIN_CORAL:
            case DEAD_BRAIN_CORAL_BLOCK:
            case DEAD_BRAIN_CORAL_FAN:
            case DEAD_BRAIN_CORAL_WALL_FAN:
            case DEAD_BUBBLE_CORAL:
            case DEAD_BUBBLE_CORAL_BLOCK:
            case DEAD_BUBBLE_CORAL_FAN:
            case DEAD_BUBBLE_CORAL_WALL_FAN:
            case DEAD_BUSH:
            case DEAD_FIRE_CORAL:
            case DEAD_FIRE_CORAL_BLOCK:
            case DEAD_FIRE_CORAL_FAN:
            case DEAD_FIRE_CORAL_WALL_FAN:
            case DEAD_HORN_CORAL:
            case DEAD_HORN_CORAL_BLOCK:
            case DEAD_HORN_CORAL_FAN:
            case DEAD_HORN_CORAL_WALL_FAN:
            case DEAD_TUBE_CORAL:
            case DEAD_TUBE_CORAL_BLOCK:
            case DEAD_TUBE_CORAL_FAN:
            case DEAD_TUBE_CORAL_WALL_FAN:
            case DECORATED_POT:
            case DEEPSLATE:
            case DEEPSLATE_BRICKS:
            case DEEPSLATE_BRICK_SLAB:
            case DEEPSLATE_BRICK_STAIRS:
            case DEEPSLATE_BRICK_WALL:
            case DEEPSLATE_COAL_ORE:
            case DEEPSLATE_COPPER_ORE:
            case DEEPSLATE_DIAMOND_ORE:
            case DEEPSLATE_EMERALD_ORE:
            case DEEPSLATE_GOLD_ORE:
            case DEEPSLATE_IRON_ORE:
            case DEEPSLATE_LAPIS_ORE:
            case DEEPSLATE_REDSTONE_ORE:
            case DEEPSLATE_TILES:
            case DEEPSLATE_TILE_SLAB:
            case DEEPSLATE_TILE_STAIRS:
            case DEEPSLATE_TILE_WALL:
            case DETECTOR_RAIL:
            case DIAMOND_BLOCK:
            case DIAMOND_ORE:
            case DIORITE:
            case DIORITE_SLAB:
            case DIORITE_STAIRS:
            case DIORITE_WALL:
            case DIRT:
            case DIRT_PATH:
            case DISPENSER:
            case DRAGON_EGG:
            case DRAGON_HEAD:
            case DRAGON_WALL_HEAD:
            case DRIED_KELP_BLOCK:
            case DRIPSTONE_BLOCK:
            case DROPPER:
            case EMERALD_BLOCK:
            case EMERALD_ORE:
            case ENCHANTING_TABLE:
            case ENDER_CHEST:
            case END_GATEWAY:
            case END_PORTAL:
            case END_PORTAL_FRAME:
            case END_ROD:
            case END_STONE:
            case END_STONE_BRICKS:
            case END_STONE_BRICK_SLAB:
            case END_STONE_BRICK_STAIRS:
            case END_STONE_BRICK_WALL:
            case EXPOSED_COPPER:
            case EXPOSED_CUT_COPPER:
            case EXPOSED_CUT_COPPER_SLAB:
            case EXPOSED_CUT_COPPER_STAIRS:
            case FARMLAND:
            case FERN:
            case FIRE:
            case FIRE_CORAL:
            case FIRE_CORAL_BLOCK:
            case FIRE_CORAL_FAN:
            case FIRE_CORAL_WALL_FAN:
            case FLETCHING_TABLE:
            case FLOWERING_AZALEA:
            case FLOWERING_AZALEA_LEAVES:
            case FLOWER_POT:
            case FROGSPAWN:
            case FROSTED_ICE:
            case FURNACE:
            case GILDED_BLACKSTONE:
            case GLASS:
            case GLASS_PANE:
            case GLOWSTONE:
            case GLOW_LICHEN:
            case GOLD_BLOCK:
            case GOLD_ORE:
            case GRANITE:
            case GRANITE_SLAB:
            case GRANITE_STAIRS:
            case GRANITE_WALL:
            case GRASS:
            case GRASS_BLOCK:
            case GRAVEL:
            case GRAY_BANNER:
            case GRAY_BED:
            case GRAY_CANDLE:
            case GRAY_CANDLE_CAKE:
            case GRAY_CARPET:
            case GRAY_CONCRETE:
            case GRAY_CONCRETE_POWDER:
            case GRAY_GLAZED_TERRACOTTA:
            case GRAY_SHULKER_BOX:
            case GRAY_STAINED_GLASS:
            case GRAY_STAINED_GLASS_PANE:
            case GRAY_TERRACOTTA:
            case GRAY_WALL_BANNER:
            case GRAY_WOOL:
            case GREEN_BANNER:
            case GREEN_BED:
            case GREEN_CANDLE:
            case GREEN_CANDLE_CAKE:
            case GREEN_CARPET:
            case GREEN_CONCRETE:
            case GREEN_CONCRETE_POWDER:
            case GREEN_GLAZED_TERRACOTTA:
            case GREEN_SHULKER_BOX:
            case GREEN_STAINED_GLASS:
            case GREEN_STAINED_GLASS_PANE:
            case GREEN_TERRACOTTA:
            case GREEN_WALL_BANNER:
            case GREEN_WOOL:
            case GRINDSTONE:
            case HANGING_ROOTS:
            case HAY_BLOCK:
            case HEAVY_WEIGHTED_PRESSURE_PLATE:
            case HONEYCOMB_BLOCK:
            case HONEY_BLOCK:
            case HOPPER:
            case HORN_CORAL:
            case HORN_CORAL_BLOCK:
            case HORN_CORAL_FAN:
            case HORN_CORAL_WALL_FAN:
            case ICE:
            case INFESTED_CHISELED_STONE_BRICKS:
            case INFESTED_COBBLESTONE:
            case INFESTED_CRACKED_STONE_BRICKS:
            case INFESTED_DEEPSLATE:
            case INFESTED_MOSSY_STONE_BRICKS:
            case INFESTED_STONE:
            case INFESTED_STONE_BRICKS:
            case IRON_BARS:
            case IRON_BLOCK:
            case IRON_DOOR:
            case IRON_ORE:
            case IRON_TRAPDOOR:
            case JACK_O_LANTERN:
            case JIGSAW:
            case JUKEBOX:
            case JUNGLE_BUTTON:
            case JUNGLE_DOOR:
            case JUNGLE_FENCE:
            case JUNGLE_FENCE_GATE:
            case JUNGLE_HANGING_SIGN:
            case JUNGLE_LEAVES:
            case JUNGLE_LOG:
            case JUNGLE_PLANKS:
            case JUNGLE_PRESSURE_PLATE:
            case JUNGLE_SAPLING:
            case JUNGLE_SIGN:
            case JUNGLE_SLAB:
            case JUNGLE_STAIRS:
            case JUNGLE_TRAPDOOR:
            case JUNGLE_WALL_HANGING_SIGN:
            case JUNGLE_WALL_SIGN:
            case JUNGLE_WOOD:
            case KELP:
            case KELP_PLANT:
            case LADDER:
            case LANTERN:
            case LAPIS_BLOCK:
            case LAPIS_ORE:
            case LARGE_AMETHYST_BUD:
            case LARGE_FERN:
            case LAVA:
            case LAVA_CAULDRON:
            case LECTERN:
            case LEVER:
            case LIGHT:
            case LIGHTNING_ROD:
            case LIGHT_BLUE_BANNER:
            case LIGHT_BLUE_BED:
            case LIGHT_BLUE_CANDLE:
            case LIGHT_BLUE_CANDLE_CAKE:
            case LIGHT_BLUE_CARPET:
            case LIGHT_BLUE_CONCRETE:
            case LIGHT_BLUE_CONCRETE_POWDER:
            case LIGHT_BLUE_GLAZED_TERRACOTTA:
            case LIGHT_BLUE_SHULKER_BOX:
            case LIGHT_BLUE_STAINED_GLASS:
            case LIGHT_BLUE_STAINED_GLASS_PANE:
            case LIGHT_BLUE_TERRACOTTA:
            case LIGHT_BLUE_WALL_BANNER:
            case LIGHT_BLUE_WOOL:
            case LIGHT_GRAY_BANNER:
            case LIGHT_GRAY_BED:
            case LIGHT_GRAY_CANDLE:
            case LIGHT_GRAY_CANDLE_CAKE:
            case LIGHT_GRAY_CARPET:
            case LIGHT_GRAY_CONCRETE:
            case LIGHT_GRAY_CONCRETE_POWDER:
            case LIGHT_GRAY_GLAZED_TERRACOTTA:
            case LIGHT_GRAY_SHULKER_BOX:
            case LIGHT_GRAY_STAINED_GLASS:
            case LIGHT_GRAY_STAINED_GLASS_PANE:
            case LIGHT_GRAY_TERRACOTTA:
            case LIGHT_GRAY_WALL_BANNER:
            case LIGHT_GRAY_WOOL:
            case LIGHT_WEIGHTED_PRESSURE_PLATE:
            case LILAC:
            case LILY_OF_THE_VALLEY:
            case LILY_PAD:
            case LIME_BANNER:
            case LIME_BED:
            case LIME_CANDLE:
            case LIME_CANDLE_CAKE:
            case LIME_CARPET:
            case LIME_CONCRETE:
            case LIME_CONCRETE_POWDER:
            case LIME_GLAZED_TERRACOTTA:
            case LIME_SHULKER_BOX:
            case LIME_STAINED_GLASS:
            case LIME_STAINED_GLASS_PANE:
            case LIME_TERRACOTTA:
            case LIME_WALL_BANNER:
            case LIME_WOOL:
            case LODESTONE:
            case LOOM:
            case MAGENTA_BANNER:
            case MAGENTA_BED:
            case MAGENTA_CANDLE:
            case MAGENTA_CANDLE_CAKE:
            case MAGENTA_CARPET:
            case MAGENTA_CONCRETE:
            case MAGENTA_CONCRETE_POWDER:
            case MAGENTA_GLAZED_TERRACOTTA:
            case MAGENTA_SHULKER_BOX:
            case MAGENTA_STAINED_GLASS:
            case MAGENTA_STAINED_GLASS_PANE:
            case MAGENTA_TERRACOTTA:
            case MAGENTA_WALL_BANNER:
            case MAGENTA_WOOL:
            case MAGMA_BLOCK:
            case MANGROVE_BUTTON:
            case MANGROVE_DOOR:
            case MANGROVE_FENCE:
            case MANGROVE_FENCE_GATE:
            case MANGROVE_HANGING_SIGN:
            case MANGROVE_LEAVES:
            case MANGROVE_LOG:
            case MANGROVE_PLANKS:
            case MANGROVE_PRESSURE_PLATE:
            case MANGROVE_PROPAGULE:
            case MANGROVE_ROOTS:
            case MANGROVE_SIGN:
            case MANGROVE_SLAB:
            case MANGROVE_STAIRS:
            case MANGROVE_TRAPDOOR:
            case MANGROVE_WALL_HANGING_SIGN:
            case MANGROVE_WALL_SIGN:
            case MANGROVE_WOOD:
            case MEDIUM_AMETHYST_BUD:
            case MELON:
            case MELON_STEM:
            case MOSSY_COBBLESTONE:
            case MOSSY_COBBLESTONE_SLAB:
            case MOSSY_COBBLESTONE_STAIRS:
            case MOSSY_COBBLESTONE_WALL:
            case MOSSY_STONE_BRICKS:
            case MOSSY_STONE_BRICK_SLAB:
            case MOSSY_STONE_BRICK_STAIRS:
            case MOSSY_STONE_BRICK_WALL:
            case MOSS_BLOCK:
            case MOSS_CARPET:
            case MOVING_PISTON:
            case MUD:
            case MUDDY_MANGROVE_ROOTS:
            case MUD_BRICKS:
            case MUD_BRICK_SLAB:
            case MUD_BRICK_STAIRS:
            case MUD_BRICK_WALL:
            case MUSHROOM_STEM:
            case MYCELIUM:
            case NETHERITE_BLOCK:
            case NETHERRACK:
            case NETHER_BRICKS:
            case NETHER_BRICK_FENCE:
            case NETHER_BRICK_SLAB:
            case NETHER_BRICK_STAIRS:
            case NETHER_BRICK_WALL:
            case NETHER_GOLD_ORE:
            case NETHER_PORTAL:
            case NETHER_QUARTZ_ORE:
            case NETHER_SPROUTS:
            case NETHER_WART:
            case NETHER_WART_BLOCK:
            case NOTE_BLOCK:
            case OAK_BUTTON:
            case OAK_DOOR:
            case OAK_FENCE:
            case OAK_FENCE_GATE:
            case OAK_HANGING_SIGN:
            case OAK_LEAVES:
            case OAK_LOG:
            case OAK_PLANKS:
            case OAK_PRESSURE_PLATE:
            case OAK_SAPLING:
            case OAK_SIGN:
            case OAK_SLAB:
            case OAK_STAIRS:
            case OAK_TRAPDOOR:
            case OAK_WALL_HANGING_SIGN:
            case OAK_WALL_SIGN:
            case OAK_WOOD:
            case OBSERVER:
            case OBSIDIAN:
            case OCHRE_FROGLIGHT:
            case ORANGE_BANNER:
            case ORANGE_BED:
            case ORANGE_CANDLE:
            case ORANGE_CANDLE_CAKE:
            case ORANGE_CARPET:
            case ORANGE_CONCRETE:
            case ORANGE_CONCRETE_POWDER:
            case ORANGE_GLAZED_TERRACOTTA:
            case ORANGE_SHULKER_BOX:
            case ORANGE_STAINED_GLASS:
            case ORANGE_STAINED_GLASS_PANE:
            case ORANGE_TERRACOTTA:
            case ORANGE_TULIP:
            case ORANGE_WALL_BANNER:
            case ORANGE_WOOL:
            case OXEYE_DAISY:
            case OXIDIZED_COPPER:
            case OXIDIZED_CUT_COPPER:
            case OXIDIZED_CUT_COPPER_SLAB:
            case OXIDIZED_CUT_COPPER_STAIRS:
            case PACKED_ICE:
            case PACKED_MUD:
            case PEARLESCENT_FROGLIGHT:
            case PEONY:
            case PETRIFIED_OAK_SLAB:
            case PIGLIN_HEAD:
            case PIGLIN_WALL_HEAD:
            case PINK_BANNER:
            case PINK_BED:
            case PINK_CANDLE:
            case PINK_CANDLE_CAKE:
            case PINK_CARPET:
            case PINK_CONCRETE:
            case PINK_CONCRETE_POWDER:
            case PINK_GLAZED_TERRACOTTA:
            case PINK_PETALS:
            case PINK_SHULKER_BOX:
            case PINK_STAINED_GLASS:
            case PINK_STAINED_GLASS_PANE:
            case PINK_TERRACOTTA:
            case PINK_TULIP:
            case PINK_WALL_BANNER:
            case PINK_WOOL:
            case PISTON:
            case PISTON_HEAD:
            case PITCHER_CROP:
            case PITCHER_PLANT:
            case PLAYER_HEAD:
            case PLAYER_WALL_HEAD:
            case PODZOL:
            case POINTED_DRIPSTONE:
            case POLISHED_ANDESITE:
            case POLISHED_ANDESITE_SLAB:
            case POLISHED_ANDESITE_STAIRS:
            case POLISHED_BASALT:
            case POLISHED_BLACKSTONE:
            case POLISHED_BLACKSTONE_BRICKS:
            case POLISHED_BLACKSTONE_BRICK_SLAB:
            case POLISHED_BLACKSTONE_BRICK_STAIRS:
            case POLISHED_BLACKSTONE_BRICK_WALL:
            case POLISHED_BLACKSTONE_BUTTON:
            case POLISHED_BLACKSTONE_PRESSURE_PLATE:
            case POLISHED_BLACKSTONE_SLAB:
            case POLISHED_BLACKSTONE_STAIRS:
            case POLISHED_BLACKSTONE_WALL:
            case POLISHED_DEEPSLATE:
            case POLISHED_DEEPSLATE_SLAB:
            case POLISHED_DEEPSLATE_STAIRS:
            case POLISHED_DEEPSLATE_WALL:
            case POLISHED_DIORITE:
            case POLISHED_DIORITE_SLAB:
            case POLISHED_DIORITE_STAIRS:
            case POLISHED_GRANITE:
            case POLISHED_GRANITE_SLAB:
            case POLISHED_GRANITE_STAIRS:
            case POPPY:
            case POTATOES:
            case POTTED_ACACIA_SAPLING:
            case POTTED_ALLIUM:
            case POTTED_AZALEA_BUSH:
            case POTTED_AZURE_BLUET:
            case POTTED_BAMBOO:
            case POTTED_BIRCH_SAPLING:
            case POTTED_BLUE_ORCHID:
            case POTTED_BROWN_MUSHROOM:
            case POTTED_CACTUS:
            case POTTED_CHERRY_SAPLING:
            case POTTED_CORNFLOWER:
            case POTTED_CRIMSON_FUNGUS:
            case POTTED_CRIMSON_ROOTS:
            case POTTED_DANDELION:
            case POTTED_DARK_OAK_SAPLING:
            case POTTED_DEAD_BUSH:
            case POTTED_FERN:
            case POTTED_FLOWERING_AZALEA_BUSH:
            case POTTED_JUNGLE_SAPLING:
            case POTTED_LILY_OF_THE_VALLEY:
            case POTTED_MANGROVE_PROPAGULE:
            case POTTED_OAK_SAPLING:
            case POTTED_ORANGE_TULIP:
            case POTTED_OXEYE_DAISY:
            case POTTED_PINK_TULIP:
            case POTTED_POPPY:
            case POTTED_RED_MUSHROOM:
            case POTTED_RED_TULIP:
            case POTTED_SPRUCE_SAPLING:
            case POTTED_TORCHFLOWER:
            case POTTED_WARPED_FUNGUS:
            case POTTED_WARPED_ROOTS:
            case POTTED_WHITE_TULIP:
            case POTTED_WITHER_ROSE:
            case POWDER_SNOW:
            case POWDER_SNOW_CAULDRON:
            case POWERED_RAIL:
            case PRISMARINE:
            case PRISMARINE_BRICKS:
            case PRISMARINE_BRICK_SLAB:
            case PRISMARINE_BRICK_STAIRS:
            case PRISMARINE_SLAB:
            case PRISMARINE_STAIRS:
            case PRISMARINE_WALL:
            case PUMPKIN:
            case PUMPKIN_STEM:
            case PURPLE_BANNER:
            case PURPLE_BED:
            case PURPLE_CANDLE:
            case PURPLE_CANDLE_CAKE:
            case PURPLE_CARPET:
            case PURPLE_CONCRETE:
            case PURPLE_CONCRETE_POWDER:
            case PURPLE_GLAZED_TERRACOTTA:
            case PURPLE_SHULKER_BOX:
            case PURPLE_STAINED_GLASS:
            case PURPLE_STAINED_GLASS_PANE:
            case PURPLE_TERRACOTTA:
            case PURPLE_WALL_BANNER:
            case PURPLE_WOOL:
            case PURPUR_BLOCK:
            case PURPUR_PILLAR:
            case PURPUR_SLAB:
            case PURPUR_STAIRS:
            case QUARTZ_BLOCK:
            case QUARTZ_BRICKS:
            case QUARTZ_PILLAR:
            case QUARTZ_SLAB:
            case QUARTZ_STAIRS:
            case RAIL:
            case RAW_COPPER_BLOCK:
            case RAW_GOLD_BLOCK:
            case RAW_IRON_BLOCK:
            case REDSTONE_BLOCK:
            case REDSTONE_LAMP:
            case REDSTONE_ORE:
            case REDSTONE_TORCH:
            case REDSTONE_WALL_TORCH:
            case REDSTONE_WIRE:
            case RED_BANNER:
            case RED_BED:
            case RED_CANDLE:
            case RED_CANDLE_CAKE:
            case RED_CARPET:
            case RED_CONCRETE:
            case RED_CONCRETE_POWDER:
            case RED_GLAZED_TERRACOTTA:
            case RED_MUSHROOM:
            case RED_MUSHROOM_BLOCK:
            case RED_NETHER_BRICKS:
            case RED_NETHER_BRICK_SLAB:
            case RED_NETHER_BRICK_STAIRS:
            case RED_NETHER_BRICK_WALL:
            case RED_SAND:
            case RED_SANDSTONE:
            case RED_SANDSTONE_SLAB:
            case RED_SANDSTONE_STAIRS:
            case RED_SANDSTONE_WALL:
            case RED_SHULKER_BOX:
            case RED_STAINED_GLASS:
            case RED_STAINED_GLASS_PANE:
            case RED_TERRACOTTA:
            case RED_TULIP:
            case RED_WALL_BANNER:
            case RED_WOOL:
            case REINFORCED_DEEPSLATE:
            case REPEATER:
            case REPEATING_COMMAND_BLOCK:
            case RESPAWN_ANCHOR:
            case ROOTED_DIRT:
            case ROSE_BUSH:
            case SAND:
            case SANDSTONE:
            case SANDSTONE_SLAB:
            case SANDSTONE_STAIRS:
            case SANDSTONE_WALL:
            case SCAFFOLDING:
            case SCULK:
            case SCULK_CATALYST:
            case SCULK_SENSOR:
            case SCULK_SHRIEKER:
            case SCULK_VEIN:
            case SEAGRASS:
            case SEA_LANTERN:
            case SEA_PICKLE:
            case SHROOMLIGHT:
            case SHULKER_BOX:
            case SKELETON_SKULL:
            case SKELETON_WALL_SKULL:
            case SLIME_BLOCK:
            case SMALL_AMETHYST_BUD:
            case SMALL_DRIPLEAF:
            case SMITHING_TABLE:
            case SMOKER:
            case SMOOTH_BASALT:
            case SMOOTH_QUARTZ:
            case SMOOTH_QUARTZ_SLAB:
            case SMOOTH_QUARTZ_STAIRS:
            case SMOOTH_RED_SANDSTONE:
            case SMOOTH_RED_SANDSTONE_SLAB:
            case SMOOTH_RED_SANDSTONE_STAIRS:
            case SMOOTH_SANDSTONE:
            case SMOOTH_SANDSTONE_SLAB:
            case SMOOTH_SANDSTONE_STAIRS:
            case SMOOTH_STONE:
            case SMOOTH_STONE_SLAB:
            case SNIFFER_EGG:
            case SNOW:
            case SNOW_BLOCK:
            case SOUL_CAMPFIRE:
            case SOUL_FIRE:
            case SOUL_LANTERN:
            case SOUL_SAND:
            case SOUL_SOIL:
            case SOUL_TORCH:
            case SOUL_WALL_TORCH:
            case SPAWNER:
            case SPONGE:
            case SPORE_BLOSSOM:
            case SPRUCE_BUTTON:
            case SPRUCE_DOOR:
            case SPRUCE_FENCE:
            case SPRUCE_FENCE_GATE:
            case SPRUCE_HANGING_SIGN:
            case SPRUCE_LEAVES:
            case SPRUCE_LOG:
            case SPRUCE_PLANKS:
            case SPRUCE_PRESSURE_PLATE:
            case SPRUCE_SAPLING:
            case SPRUCE_SIGN:
            case SPRUCE_SLAB:
            case SPRUCE_STAIRS:
            case SPRUCE_TRAPDOOR:
            case SPRUCE_WALL_HANGING_SIGN:
            case SPRUCE_WALL_SIGN:
            case SPRUCE_WOOD:
            case STICKY_PISTON:
            case STONE:
            case STONECUTTER:
            case STONE_BRICKS:
            case STONE_BRICK_SLAB:
            case STONE_BRICK_STAIRS:
            case STONE_BRICK_WALL:
            case STONE_BUTTON:
            case STONE_PRESSURE_PLATE:
            case STONE_SLAB:
            case STONE_STAIRS:
            case STRIPPED_ACACIA_LOG:
            case STRIPPED_ACACIA_WOOD:
            case STRIPPED_BAMBOO_BLOCK:
            case STRIPPED_BIRCH_LOG:
            case STRIPPED_BIRCH_WOOD:
            case STRIPPED_CHERRY_LOG:
            case STRIPPED_CHERRY_WOOD:
            case STRIPPED_CRIMSON_HYPHAE:
            case STRIPPED_CRIMSON_STEM:
            case STRIPPED_DARK_OAK_LOG:
            case STRIPPED_DARK_OAK_WOOD:
            case STRIPPED_JUNGLE_LOG:
            case STRIPPED_JUNGLE_WOOD:
            case STRIPPED_MANGROVE_LOG:
            case STRIPPED_MANGROVE_WOOD:
            case STRIPPED_OAK_LOG:
            case STRIPPED_OAK_WOOD:
            case STRIPPED_SPRUCE_LOG:
            case STRIPPED_SPRUCE_WOOD:
            case STRIPPED_WARPED_HYPHAE:
            case STRIPPED_WARPED_STEM:
            case STRUCTURE_BLOCK:
            case STRUCTURE_VOID:
            case SUGAR_CANE:
            case SUNFLOWER:
            case SUSPICIOUS_GRAVEL:
            case SUSPICIOUS_SAND:
            case SWEET_BERRY_BUSH:
            case TALL_GRASS:
            case TALL_SEAGRASS:
            case TARGET:
            case TERRACOTTA:
            case TINTED_GLASS:
            case TNT:
            case TORCH:
            case TORCHFLOWER:
            case TORCHFLOWER_CROP:
            case TRAPPED_CHEST:
            case TRIPWIRE:
            case TRIPWIRE_HOOK:
            case TUBE_CORAL:
            case TUBE_CORAL_BLOCK:
            case TUBE_CORAL_FAN:
            case TUBE_CORAL_WALL_FAN:
            case TUFF:
            case TURTLE_EGG:
            case TWISTING_VINES:
            case TWISTING_VINES_PLANT:
            case VERDANT_FROGLIGHT:
            case VINE:
            case VOID_AIR:
            case WALL_TORCH:
            case WARPED_BUTTON:
            case WARPED_DOOR:
            case WARPED_FENCE:
            case WARPED_FENCE_GATE:
            case WARPED_FUNGUS:
            case WARPED_HANGING_SIGN:
            case WARPED_HYPHAE:
            case WARPED_NYLIUM:
            case WARPED_PLANKS:
            case WARPED_PRESSURE_PLATE:
            case WARPED_ROOTS:
            case WARPED_SIGN:
            case WARPED_SLAB:
            case WARPED_STAIRS:
            case WARPED_STEM:
            case WARPED_TRAPDOOR:
            case WARPED_WALL_HANGING_SIGN:
            case WARPED_WALL_SIGN:
            case WARPED_WART_BLOCK:
            case WATER:
            case WATER_CAULDRON:
            case WAXED_COPPER_BLOCK:
            case WAXED_CUT_COPPER:
            case WAXED_CUT_COPPER_SLAB:
            case WAXED_CUT_COPPER_STAIRS:
            case WAXED_EXPOSED_COPPER:
            case WAXED_EXPOSED_CUT_COPPER:
            case WAXED_EXPOSED_CUT_COPPER_SLAB:
            case WAXED_EXPOSED_CUT_COPPER_STAIRS:
            case WAXED_OXIDIZED_COPPER:
            case WAXED_OXIDIZED_CUT_COPPER:
            case WAXED_OXIDIZED_CUT_COPPER_SLAB:
            case WAXED_OXIDIZED_CUT_COPPER_STAIRS:
            case WAXED_WEATHERED_COPPER:
            case WAXED_WEATHERED_CUT_COPPER:
            case WAXED_WEATHERED_CUT_COPPER_SLAB:
            case WAXED_WEATHERED_CUT_COPPER_STAIRS:
            case WEATHERED_COPPER:
            case WEATHERED_CUT_COPPER:
            case WEATHERED_CUT_COPPER_SLAB:
            case WEATHERED_CUT_COPPER_STAIRS:
            case WEEPING_VINES:
            case WEEPING_VINES_PLANT:
            case WET_SPONGE:
            case WHEAT:
            case WHITE_BANNER:
            case WHITE_BED:
            case WHITE_CANDLE:
            case WHITE_CANDLE_CAKE:
            case WHITE_CARPET:
            case WHITE_CONCRETE:
            case WHITE_CONCRETE_POWDER:
            case WHITE_GLAZED_TERRACOTTA:
            case WHITE_SHULKER_BOX:
            case WHITE_STAINED_GLASS:
            case WHITE_STAINED_GLASS_PANE:
            case WHITE_TERRACOTTA:
            case WHITE_TULIP:
            case WHITE_WALL_BANNER:
            case WHITE_WOOL:
            case WITHER_ROSE:
            case WITHER_SKELETON_SKULL:
            case WITHER_SKELETON_WALL_SKULL:
            case YELLOW_BANNER:
            case YELLOW_BED:
            case YELLOW_CANDLE:
            case YELLOW_CANDLE_CAKE:
            case YELLOW_CARPET:
            case YELLOW_CONCRETE:
            case YELLOW_CONCRETE_POWDER:
            case YELLOW_GLAZED_TERRACOTTA:
            case YELLOW_SHULKER_BOX:
            case YELLOW_STAINED_GLASS:
            case YELLOW_STAINED_GLASS_PANE:
            case YELLOW_TERRACOTTA:
            case YELLOW_WALL_BANNER:
            case YELLOW_WOOL:
            case ZOMBIE_HEAD:
            case ZOMBIE_WALL_HEAD:
                return true;
            default:
                return false;
        }
    }

}
